"""Add destination, accommodation, and transport tables

Revision ID: ca41c682be28
Revises: 
Create Date: 2025-07-10 19:24:59.709502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca41c682be28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('continent', sa.String(length=50), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('image1', sa.String(length=100), nullable=False),
    sa.Column('image2', sa.String(length=100), nullable=False),
    sa.Column('image3', sa.String(length=100), nullable=False),
    sa.Column('service_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport')
    op.drop_table('accommodation')
    op.drop_table('destination')
    # ### end Alembic commands ###
