"""Add activity column to Destination

Revision ID: f2882ea0daa9
Revises: ca41c682be28
Create Date: 2025-07-14 15:37:09.017239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2882ea0daa9'
down_revision = 'ca41c682be28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('activity')

    # ### end Alembic commands ###
